version: '3.1'

services:

  sk_example_db:
    image: postgres:14.5
    container_name: "sk_db"
    restart: always
    environment:
      POSTGRES_USER: sk_example_user
      POSTGRES_PASSWORD: superkassa
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgres/data